name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Resolve Swift Package Manager dependencies
      run: xcodebuild -resolvePackageDependencies
      working-directory: ./TMBDMovieList/MovieDBList

    - name: Build app
      run: xcodebuild clean build -project TMBDMovieList/MovieDBList.xcodeproj -scheme MovieDBList -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
