name: "iOS CI"
# name: "Build iOS app"

on:
  # manual trigger but change to any supported event
  # see addl: https://www.andrewhoog.com/post/how-to-build-react-native-android-app-with-github-actions/#3-run-build-workflow
  # addl comment
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: install dependencies
        run: |
          gem install bundler
          cd MovieDBList
          bundle install

      - name: Check if the encrypted provisioning profile exists
        run: ls -la ./
         
      - name: Decrypt provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          openssl aes-256-cbc -d -k "secret" -in profile.mobileprovision.enc -out profile.mobileprovision || echo "Decryption failed"
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "Move operation failed"

      - name: Set Xcode version
        run: |
         sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
